-- Core tables for the per-plan hash-chained evidence ledger.
-- Everything lives in plain PostgreSQL: no blockchain, no external trust service.

CREATE TABLE IF NOT EXISTS plan (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_no     VARCHAR(64)  NOT NULL UNIQUE,
    title       VARCHAR(255) NOT NULL,
    status      VARCHAR(32)  NOT NULL,
    source      VARCHAR(16)  NOT NULL DEFAULT 'NEW',  -- NEW | LEGACY
    legacy_ref  BIGINT NULL UNIQUE,                   -- original legacy_plan.id when source=LEGACY
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL
);

CREATE TABLE IF NOT EXISTS plan_evidence_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id      BIGINT       NOT NULL REFERENCES plan(id),
    -- per-plan contiguous sequence starting at 1
    seq          BIGINT       NOT NULL,
    event_type   VARCHAR(32)  NOT NULL,
    state_before VARCHAR(32)  NULL,
    state_after  VARCHAR(32)  NOT NULL,
    payload      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    -- client supplied idempotency key: one request can create at most one event
    request_id   VARCHAR(64)  NULL,
    -- SHA-256 of the client-supplied payload; same request_id with a different
    -- body is rejected as a conflict instead of being silently replayed
    request_fingerprint CHAR(64) NULL,
    prev_hash    CHAR(64)     NOT NULL,
    event_hash   CHAR(64)     NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_evidence_plan_seq UNIQUE (plan_id, seq),
    CONSTRAINT uq_evidence_request_id UNIQUE (request_id)
);

CREATE INDEX IF NOT EXISTS idx_evidence_plan_seq ON plan_evidence_event (plan_id, seq);
