-- ============================================================================
-- V1__init.sql
-- Plan lifecycle business tables + hash-chained evidence store.
-- All tables live inside the existing PostgreSQL instance; no external trust
-- anchor or blockchain is involved.
-- ============================================================================

CREATE TABLE plan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_no         VARCHAR(64)  NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_plan_no UNIQUE (plan_no)
);

CREATE TABLE plan_confirmation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id         BIGINT       NOT NULL REFERENCES plan(id),
    operator        VARCHAR(64)  NOT NULL,
    remark          VARCHAR(512),
    idempotency_key VARCHAR(128),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_confirmation_idem UNIQUE (plan_id, idempotency_key)
);

CREATE TABLE plan_mock_receipt (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id         BIGINT       NOT NULL REFERENCES plan(id),
    channel         VARCHAR(64)  NOT NULL,
    payload         VARCHAR(1024),
    idempotency_key VARCHAR(128),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_receipt_idem UNIQUE (plan_id, idempotency_key)
);

CREATE TABLE plan_rejection (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id         BIGINT       NOT NULL REFERENCES plan(id),
    reason          VARCHAR(512) NOT NULL,
    operator        VARCHAR(64)  NOT NULL,
    idempotency_key VARCHAR(128),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_rejection_idem UNIQUE (plan_id, idempotency_key)
);

CREATE TABLE plan_writeoff (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id         BIGINT       NOT NULL REFERENCES plan(id),
    operator        VARCHAR(64)  NOT NULL,
    remark          VARCHAR(512),
    idempotency_key VARCHAR(128),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_writeoff_idem UNIQUE (plan_id, idempotency_key)
);

-- ----------------------------------------------------------------------------
-- Evidence events. One strictly increasing, hash-linked sequence per plan.
-- event_hash = sha256(seq | planId | eventType | fromStatus | toStatus
--                     | prevHash | occurredAt | eventTime | sha256(payloadJson))
-- Link integrity is enforced in application logic inside a DB transaction:
-- the plan row is SELECT ... FOR UPDATE, the last event row is locked, and
-- seq/prev_hash are derived from it.
-- ----------------------------------------------------------------------------
CREATE TABLE plan_evidence_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id         BIGINT       NOT NULL REFERENCES plan(id),
    seq             INTEGER      NOT NULL,
    event_type      VARCHAR(40)  NOT NULL,
    from_status     VARCHAR(32),
    to_status       VARCHAR(32)  NOT NULL,
    prev_hash       VARCHAR(64),
    event_hash      VARCHAR(64)  NOT NULL,
    payload_json    TEXT         NOT NULL,
    payload_hash    VARCHAR(64)  NOT NULL,
    business_record_id BIGINT,
    idempotency_key VARCHAR(128),
    anchor          BOOLEAN      NOT NULL DEFAULT FALSE,
    event_time      TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evidence_seq UNIQUE (plan_id, seq),
    CONSTRAINT uk_evidence_idem UNIQUE (plan_id, idempotency_key),
    CONSTRAINT chk_anchor_null_key CHECK (anchor = FALSE OR idempotency_key IS NOT NULL),
    CONSTRAINT chk_hash_length CHECK (char_length(event_hash) = 64
                                      AND char_length(payload_hash) = 64
                                      AND char_length(prev_hash) = 64)
);

CREATE INDEX idx_evidence_plan ON plan_evidence_event(plan_id, seq);
CREATE INDEX idx_evidence_type ON plan_evidence_event(event_type);

-- ----------------------------------------------------------------------------
-- Legacy snapshot table: represents plans that pre-date the evidence system.
-- Migration reads rows that have no anchor event and writes a single ANCHOR
-- event each, WITHOUT modifying any original record.
-- ----------------------------------------------------------------------------
CREATE TABLE legacy_plan_snapshot (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_no         VARCHAR(64)  NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    legacy_created_at TIMESTAMP  NOT NULL,
    migrated_at     TIMESTAMP,
    anchor_event_id BIGINT
);
